name: Deploy MkDocs

on:
  push:
    branches:
      - Main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs pymdown-extensions ghp-import

      - name: Build MkDocs documentation
        run: mkdocs build -d site/docs

      - name: Assemble Web Landing Page and Pages API
        run: |
          cp -r web/* site/
          cp docs/CNAME site/CNAME

      - name: Deploy to GitHub Pages
        run: |
          python -m ghp_import -n -p -f -c animesaturn.lawliet.lol site
